services:
  - type: web
    name: sign-language-backend
    runtime: python
    rootDir: backend/Ahmad-Library/
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn sign_service:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0